-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES (Combines Users, Alumni, and Students)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  first_name text,
  last_name text,
  role text check (role in ('admin', 'alumnus', 'student', 'member')) default 'member',
  uin text,
  phone_number text,
  linkedin_url text,
  bio text,
  
  -- Alumni specific
  cohort_year int,
  team_affiliation text,
  profession_title text, -- Primary profession title if simple
  availability boolean default false,

  -- Student specific
  major text,
  classification text,
  resume_link text,

  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- EXPERIENCES (e.g., Internships, Jobs)
create table public.experiences (
  id bigint generated by default as identity primary key,
  title text not null,
  experience_type text, -- 'Internship', 'Full-time', etc.
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- PROFESSIONS (Fields of work)
create table public.professions (
  id bigint generated by default as identity primary key,
  title text not null, -- e.g., 'Software Engineering', 'Medicine'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- JOIN TABLE: Profile <-> Experiences
create table public.profile_experiences (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete cascade not null,
  experience_id bigint references public.experiences(id) on delete cascade not null,
  description text,
  date_received date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- JOIN TABLE: Profile <-> Professions
create table public.profile_professions (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete cascade not null,
  profession_id bigint references public.professions(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ROW LEVEL SECURITY (RLS)
alter table public.profiles enable row level security;
alter table public.experiences enable row level security;
alter table public.professions enable row level security;
alter table public.profile_experiences enable row level security;
alter table public.profile_professions enable row level security;

-- POLICIES

-- Profiles: Public can view (search directory), Users can edit own
create policy "Public profiles are viewable by everyone"
  on profiles for select
  using ( true );

create policy "Users can insert their own profile"
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile"
  on profiles for update
  using ( auth.uid() = id );

create policy "Admins can update any profile"
  on profiles for update
  using ( 
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'admin'
    )
  );

-- Experiences: Public read, Authenticated create (for suggestions?), Admin manage
create policy "Experiences are viewable by everyone"
  on experiences for select
  using ( true );

-- Professions: Public read
create policy "Professions are viewable by everyone"
  on professions for select
  using ( true );

-- Profile Experiences/Professions: Public read, User manage own
create policy "Public view profile details"
  on profile_experiences for select using ( true );

create policy "Users manage own experiences"
  on profile_experiences for all
  using ( auth.uid() = profile_id );

create policy "Public view profile professions"
  on profile_professions for select using ( true );

create policy "Users manage own professions"
  on profile_professions for all
  using ( auth.uid() = profile_id );


-- HELPER FUNCTION to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (
    id, 
    email, 
    first_name, 
    last_name,
    profession_title,
    team_affiliation,
    cohort_year,
    bio,
    linkedin_url,
    phone_number
  )
  values (
    new.id, 
    new.email,
    new.raw_user_meta_data->>'first_name',
    new.raw_user_meta_data->>'last_name',
    new.raw_user_meta_data->>'profession_title',
    new.raw_user_meta_data->>'team_affiliation',
    (new.raw_user_meta_data->>'cohort_year')::int,
    new.raw_user_meta_data->>'bio',
    new.raw_user_meta_data->>'linkedin_url',
    new.raw_user_meta_data->>'phone_number'
  );
  return new;
end;
$$ language plpgsql security definer;

-- TRIGGER for new user signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
